name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '20'  # Updated to use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Clean the project
        run: npm run clean  # Added step to clean the project

      - name: Build the project
        run: npm run build  # Build the project, docs folder as the output

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Publish directory

permissions:
  contents: write
